<?php
/**
 * @file
 * os2web_borger_dk_notifications.module
 */

/**
 * Implements hook_form_alter().
 */
function os2web_borger_dk_notifications_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'os2web_borger_dk_settings_form') {
    $form['os2web_borger_dk_notifications'] = array(
      '#type' => 'fieldset',
      '#title' => 'Notifikationer',
      '#tree' => FALSE,
      '#collapsible' => 1,
      '#group' => 'vertical_settings_tab',
    );

    $form['os2web_borger_dk_notifications']['os2web_borger_dk_notifications_send'] = array(
      '#type' => 'checkbox',
      '#title' => 'Send notifikationer til indholdsejeren ved opdatering.',
    );
  }
}

/**
 * Implements hook_node_update().
 */
function os2web_borger_dk_notifications_node_update($node) {
  if (variable_get('os2web_borger_dk_notifications_send', FALSE) && is_object($node) && $node->type == 'os2web_borger_dk_article') {
    $account = user_load($node->uid);
    $mail = $account->mail;

    $url = $nodeurl = url('node/' . $node->nid, array('absolute' => TRUE));

    $message['subject'] = 'En Borger.dk artikel er opdateret på Odsherred.dk';
    $message['body'] = $url . "\n\n";
    $message['body'] .= "Selve artiklen er sat med den emailadresse som denne email er sendt til som ejer. Såfremt det ikke er dig selv der har opdateret indholdet, må du gerne sikre dig at indholdet er som det skal være ved at besøge siden på ovenstående link.";

    drupal_mail('os2web_borger_dk_notifications', 'os2web_borger_dk_notifications_mail', $mail, $language, $message);
  }
}

/**
 * Implements hook_mail().
 */
function os2web_borger_dk_notifications_mail($key, &$message, $params) {
  $message['subject'] = $params['subject'];
  $message['body'][] = $params['body'];
}
