<?php
/**
 * @file
 * Code for the Odsherred create content page feature.
 */

include_once 'odsherred_create_content_page.features.inc';

/**
 * Implements hook_form_alter().
 */
function odsherred_create_content_page_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'contentpage_node_form'){
    $form['#validate'][] = 'odsherred_create_content_page_form_validate';
  }
}

function odsherred_create_content_page_form_validate($form, &$form_state){
  global $user;

  if(!user_access('administer site configuration') && !in_array('Administrator', $user->roles) && !in_array('Webmaster', $user->roles)){
    //drupal_set_message(print_r($form_state['input']['field_termref_sted']['und']['value_field'], TRUE));
    $sted_input = explode('" "', $form_state['input']['field_termref_sted']['und']['value_field']);

    foreach($sted_input as $sted){
      $sted = str_replace('"', "", $sted);
      if (empty($sted))
        continue;
      $sted_term = taxonomy_get_term_by_name($sted,'egennavne_stednavne');
      if (empty($sted_term)){
        form_set_error('field_termref_sted', $sted . ': ' . t('Du kan kun vælge de eksisterende navne'));
      }
    }

    //drupal_set_message(print_r($form_state['input']['field_organization']['und']['value_field'], TRUE));
    $org_input = explode('" "', $form_state['input']['field_organization']['und']['value_field']);

    foreach($org_input as $org){
      $org = str_replace('"', "", $org);
      if (empty($org))
        continue;
      $org_term = taxonomy_get_term_by_name($org,'organisation');
      if (empty($org_term)){
        form_set_error('field_organization', $org . ': ' . t('Du kan kun vælge de eksisterende organisationer'));
      }
    }
      
    //drupal_set_message(print_r($form_state['input']['field_politics']['und']['value_field'], TRUE));
    $politics_input = explode('" "', $form_state['input']['field_politics']['und']['value_field']);

    foreach($politics_input as $politics){
      $politics = str_replace('"', "", $politics);
      if (empty($politics))
        continue;
      $politics_term = taxonomy_get_term_by_name($politics,'politik');
      if (empty($politics_term)){
        form_set_error('field_politics', $politics . ': ' . t('Du kan kun vælge de eksisterende politikker'));
      }
    }

    if (!in_array('Webredaktør', $user->roles)){
      $stikord_input = explode('" "', $form_state['input']['field_editortags']['und']['value_field']);

      foreach($stikord_input as $stikord){
        $stikord = str_replace('"', "", $stikord);
        if (empty($stikord))
          continue;
        $stikord_term = taxonomy_get_term_by_name($stikord,'redaktoertags');
        if (empty($$stikord_term)){
          form_set_error('field_editortags', $stikord . ': ' . t('Du kan kun vælge de eksisterende stikorde'));
        }
      }
    }
  }
}