<?php

/**
 * @file
 * The module file
 */

/**
 * Implements hook_menu().
 */
function searchcloud_block_menu() {
  $items = array();
  $items['admin/config/search/searchcloud_block'] = array(
    'title' => 'Searchcloud block',
    'description' => 'Configure the search cloud block.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('searchcloud_block_admin'),
    'access arguments' => array('administer searchcloud'),
    'file' => 'searchcloud_block.admin.inc',
  );
  $items['admin/config/search/searchcloud_block/add'] = array(
    'title' => 'Add term',
    'description' => 'Add a term to the search cloud.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('searchcloud_block_admin_add'),
    'access arguments' => array('administer searchcloud'),
    'file' => 'searchcloud_block.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );
  $items['admin/config/search/searchcloud_block/edit'] = array(
    'title' => 'Edit term',
    'description' => 'Add a term to the search cloud.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('searchcloud_block_admin_edit'),
    'access arguments' => array('administer searchcloud'),
    'file' => 'searchcloud_block.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/search/searchcloud_block/reset'] = array(
    'title' => 'Searchcloud block reset',
    'page callback' => 'searchcloud_block_admin_reset',
    'access arguments' => array('searchcloud reset'),
    'file' => 'searchcloud_block.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/search/searchcloud_block/truncate'] = array(
    'title' => 'Searchcloud block truncate',
    'page callback' => 'searchcloud_block_admin_truncate',
    'access arguments' => array('searchcloud truncate'),
    'file' => 'searchcloud_block.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/search/searchcloud_block/hide'] = array(
    'title' => 'Searchcloud block hide',
    'page callback' => 'searchcloud_block_admin_hide',
    'access arguments' => array('administer searchcloud'),
    'file' => 'searchcloud_block.admin.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function searchcloud_block_theme() {
  return array(
    'searchcloud_block' => array(
      'variables' => array(
        'items' => array(),
      ),
    ),
  );
}

function searchcloud_block_hook_info() {
  $hooks = array(
    'searchcloud_block_get_result_alter',
    'searchcloud_block_check_keys_execute',
  );

  return array_fill_keys($hooks, array('group' => 'searchcloud_block'));
}

/**
 * Implements hook_permission().
 */
function searchcloud_block_permission() {
  return array(
    'administer searchcloud' => array(
      'title' => t('Administer searchcloud'),
      'description' => t('Administer this module.'),
    ),
    'searchcloud truncate' => array(
      'title' => t('Searchcloud truncate'),
      'description' => t('Truncate the complete searchcloud table.'),
    ),
    'searchcloud reset' => array(
      'title' => t('Searchcloud reset'),
      'description' => t('Reset the searchcloud table, this resets all counts to 0 (zero).'),
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function searchcloud_block_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'search_block_form':
    case 'search_form':
      $form['#submit'][] = 'searchcloud_block_submit_handler';
      break;
  }
}

/**
 * Added a custom submit handler.
 */
function searchcloud_block_submit_handler($form, $form_values) {
  switch ($form['#form_id']) {
    case 'search_block_form':
      $keys = $form_values['values']['search_block_form'];
      break;
    default:
      $keys = $form_values['values']['keys'];
  }
  if (!empty($keys)) {
    searchcloud_block_check_keys($keys);
  }
}

/**
 * Check for the searched keys and add or update them in our table.
 */
function searchcloud_block_check_keys($key) {
  $result = searchcloud_block_get_result(TRUE, $key);
  $rowcount = $result->rowCount();
  if (!empty($rowcount)) {
    foreach ($result as $record) {
      db_update('searchcloud_block_count')
      ->fields(array('count' => $record->count + 1))
      ->condition('keyword', $key)
      ->execute();
    }
  }
  else {
    db_insert('searchcloud_block_count')
    ->fields(array(
      'keyword' => $key,
      'count' => 1,
    ))
    ->execute();
  }

  // save parameters
  $_key = $key;
  $_count = $record->count + 1;

  // execute hook
  module_invoke_all('searchcloud_block_check_keys_execute', $_key, $_count);
}

function searchcloud_block_get_result($all = FALSE, $key = FALSE, $nr = FALSE, $order = FALSE) {
  try {
  $query = db_select('searchcloud_block_count', 'sbc');
  $query->fields('sbc', array('keyword', 'count', 'hide'));

  if ($key) {
    $query->condition('sbc.keyword', $key);
  }

  if (!$all) {
    $query->condition('sbc.hide', 1, '<>');
  }

  if ($nr) {
    $query->range(0, $nr);
  }

  if ($order) {
    $query->orderBy('count', 'DESC');
  }

    module_invoke_all('searchcloud_block_get_result_alter', $query);

  // dsm($query->__toString());
  $result = $query->execute();
  } catch(Exception $e) {
    watchdog('searchcloud_block', $e);
  }

  return $result;
}

/**
 * Implements hook_block_info().
 */
function searchcloud_block_block_info() {
  $blocks = array();
  $blocks['searchcloud_block']['info'] = 'Searchcloud block';
  $blocks['searchcloud_block']['cache'] = DRUPAL_CACHE_GLOBAL;
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function searchcloud_block_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'searchcloud_block':
      $content = searchcloud_block_get_keys();
      if ($content) {
        $block['subject'] = t('Searchcloud');
        $block['content'] = searchcloud_block_get_keys();
      }
      break;
  }
  return $block;
}

function searchcloud_block_get_keys() {
  drupal_add_css(drupal_get_path('module', 'searchcloud_block') . '/css/searchcloud_block.css');
  $nr = variable_get('searchcloud_block_count', 10);
  $stylecount = variable_get('searchcloud_block_stylecount', 5);
  $default_search = search_get_default_module_info();

  $override_search = variable_get('searchcloud_block_overridepath');
  if (!empty($override_search)) {
    $root_search_path = $override_search;
  } else {
    $root_search_path = rtrim('search/' . $default_search['path'], '/');
  }

  $result = searchcloud_block_get_result(FALSE, FALSE, $nr, TRUE);
  $items = array();

  $max = 0;
  $min = 9999;
  $rows = array();
  foreach ($result as $row) {
    $rows[] = $row;
    if ($row->count > $max) {
      $max = $row->count;
    }
    if (!isset($min) || $row->count < $min) {
      $min = $row->count;
    }
  }
  if (!empty($rows)) {
    $stepsize = 1;
    if (count($rows) > 1) {
      $stepsize = ceil(($max - $min) / $stylecount);
      shuffle($rows);
    }
    if ($stepsize < 1) {
      $stepsize = 1;
    }

    foreach ($rows as $row) {
      $ratio = $row->count / $stepsize;
      $ratio =  ceil($ratio);
      $items[] = (object)array(
        'param' => $row->keyword,
        'ratio' => $ratio,
        'row' => $row,
        'path' => rtrim($root_search_path, '/'),
      );
    }

    return theme('searchcloud_block', array('items' => $items));
  }
  else {
    return FALSE;
  }
}

function theme_searchcloud_block(&$variables) {
  $html = '<ul class="searchcloud">';

  foreach($variables['items'] as $item) {
    $html .= '<li class="cloud-' . $item->ratio . '">' . l($item->row->keyword, $item->path . '/' . $item->param) . '</li>';
  }

  return $html . '</ul>';
}

/**
 * Enable apachesolr integration
 *
 * @param SolrBaseQuery $query
 */
function searchcloud_block_apachesolr_query_alter(SolrBaseQuery $query) {
  $params = $query->getParams();

  // search query is at $params['q']
  searchcloud_block_check_keys($params['q']);

}

/**
 * Enable search_api
 *
 * @param SearchApiQueryInterface $query
 */
function searchcloud_block_search_api_query_alter(SearchApiQueryInterface $query) {
  $keys = $query->getKeys();

  if (empty($keys['#conjunction'])) {
    return;
  }

  if (strtoupper($keys['#conjunction']) != 'AND') {
    watchdog('searchcloud_block', 'At searchcloud_block_search_api_query_alter:
      unknown #conjunction parameter. Please create an issue at our project page
      at drupal.org. The unknown parameter is [' . $keys['#conjunction'] . ']');
  }

  unset($keys['#conjunction']);
  $key = trim(implode(' ', array_values($keys)));

  // update the database.
  searchcloud_block_check_keys($key);
}
