<?php

/**
 * Implements hook_filter_info().
 */
function float_filter_filter_info() {
  $filters['float_filter'] = array(
    'title'             => t('Float filter'),
    'description'       => t('Wrap floated images and tables into <span> or <div> tags.'),
    'process callback'  => '_float_filter_process',
    'default settings'  => array(
      'img_tag'   => 'span',
      'table_tag' => 'div',
    ),
    'settings callback' => '_float_filter_settings',
  );
  return $filters;
}

/**
 * Settings callback for Float filter
 */
function _float_filter_settings($form, $form_state, $filter, $format, $defaults) {
  $settings['img_tag'] = array(
    '#type'           => 'select',
    '#title'          => t('Wrapper tag for images'),
    '#empty_value'    => 0,
    '#options'        => array(
      'div'   => 'div',
      'span'  => 'span',
    ),
    '#default_value'  => isset($filter->settings['img_tag']) ? $filter->settings['img_tag'] : $defaults['img_tag'],
  );
  $settings['table_tag'] = array(
    '#type'           => 'select',
    '#title'          => t('Wrapper tag for tables'),
    '#empty_value'    => 0,
    '#options'        => array(
      'div'   => 'div',
      'span'  => 'span',
    ),
    '#default_value'  => isset($filter->settings['table_tag']) ? $filter->settings['table_tag'] : $defaults['table_tag'],
  );
  return $settings;
}

/**
 * Scan code and adds span to floats
 *
 * @param $string
 *  Text, maybe containing floats.
 * @return
 *  The input text with added markup.
 */
function _float_filter_process($text, $filter, $format) {
  if ($filter->settings['img_tag']) {
    $text = preg_replace("/<img(.*)float:(.*)(right|left)(.*)\/>/U", "<" . $filter->settings['img_tag'] . " class=\"float$3\"><img$1float:$3$4 /></" . $filter->settings['img_tag'] . ">", $text);
    $text = preg_replace("/<img(.*)align=\"(right|left)\"(.*)\/>/U", "<" . $filter->settings['img_tag'] . " class=\"float$2\"><img$1align=\"$2\"$3 /></" . $filter->settings['img_tag'] . ">", $text);
  }
  if ($filter->settings['table_tag']) {
    $text = preg_replace("/<table(.*)float:(.*)(right|left)(.*)>(.*)<\/table>/msU", "<" . $filter->settings['table_tag'] . " class=\"float$3\"><table$1float:$3$4>$5</table></" . $filter->settings['table_tag'] . ">", $text);
    $text = preg_replace("/<table(.*)align=\"(right|left)\"(.*)>(.*)<\/table>/msU", "<" . $filter->settings['table_tag'] . " class=\"float$2\"><table$1align=\"$2\"$3>$4</table></" . $filter->settings['table_tag'] . ">", $text);
  }
  return $text;
}
