<?php
/**
 * @file
 * Code for the Nyheder feature.
 */

include_once 'nyheder.features.inc';


/**
 * Implements hook_form_FORM_ID_alter().
 */
function nyheder_form_news_node_form_alter(&$form, &$form_state, $form_id) {

  // Add a new validator to the node form
  $form['#validate'][] = 'nyheder_date_validation';
}


/**
 * Validation form for dates on content type Nyheder
 *
 * @param $form
 * @param $form_state
 */
function nyheder_date_validation($form, &$form_state) {
  global $user;

  // Only validate if logged in user doesn't have the 'Ingen datovalidering' role
  if (in_array('Ingen datovalidering', $user->roles)) {
    return;
  }

  // We must validate the date fields for this user
  $start_date = strtotime($form_state['values']['field_newstypedato'][LANGUAGE_NONE][0]['value']);
  $end_date   = strtotime($form_state['values']['field_udloebsdato'][LANGUAGE_NONE][0]['value']);

  if ($start_date > $end_date) {
    form_set_error('field_newstypedato', t('Udgivelsesdato skal være tidligere end udløbsdato.'));
  }
}