<?php
/**
 * @file
 * borger_dk_integration.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function borger_dk_integration_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_borger_permalink'
  $field_bases['field_borger_permalink'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_borger_permalink',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 600,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_is_subsite'
  $field_bases['field_is_subsite'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_is_subsite',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        0 => 0,
        1 => 1,
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_boolean',
  );

  // Exported field_base: 'field_os2web_base_field_contact'
  $field_bases['field_os2web_base_field_contact'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_os2web_base_field_contact',
    'indexes' => array(
      'nid' => array(
        0 => 'nid',
      ),
    ),
    'locked' => 0,
    'module' => 'node_reference',
    'settings' => array(
      'referenceable_types' => array(
        'borger_dk_permalink' => 0,
        'borgerservices' => 0,
        'contentpage' => 0,
        'esdh_dokument' => 0,
        'esdh_sag' => 0,
        'files' => 0,
        'galleri' => 0,
        'iframe_selvbetjeningsl_sning_mm' => 0,
        'institution' => 0,
        'knactivity' => 0,
        'kontaktblok' => 'kontaktblok',
        'local_plan' => 0,
        'media' => 0,
        'news' => 0,
        'ofir_job' => 0,
        'panel' => 0,
        'person' => 0,
        'politician' => 0,
        'referat' => 0,
        'right_column' => 0,
        'rotating_image' => 0,
        'selvbetjeningslinks' => 0,
        'spotbox' => 0,
        'tema' => 0,
        'webform' => 0,
      ),
      'view' => array(
        'args' => array(),
        'display_name' => '',
        'view_name' => '',
      ),
    ),
    'translatable' => 0,
    'type' => 'node_reference',
  );

  // Exported field_base: 'field_os2web_base_field_ref_node'
  $field_bases['field_os2web_base_field_ref_node'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_os2web_base_field_ref_node',
    'indexes' => array(
      'nid' => array(
        0 => 'nid',
      ),
    ),
    'locked' => 0,
    'module' => 'node_reference',
    'settings' => array(
      'referenceable_types' => array(
        'borger_dk_permalink' => 0,
        'contentpage' => 'contentpage',
        'esdh_dokument' => 0,
        'esdh_sag' => 0,
        'files' => 0,
        'galleri' => 0,
        'iframe_selvbetjeningsl_sning_mm' => 'iframe_selvbetjeningsl_sning_mm',
        'institution' => 0,
        'knactivity' => 0,
        'kontaktblok' => 0,
        'local_plan' => 0,
        'media' => 0,
        'news' => 0,
        'ofir_job' => 0,
        'panel' => 0,
        'person' => 0,
        'politician' => 0,
        'referat' => 0,
        'right_column' => 0,
        'rotating_image' => 0,
        'selvbetjeningslinks' => 0,
        'spotbox' => 0,
        'tema' => 0,
        'webform' => 0,
      ),
      'view' => array(
        'args' => array(),
        'display_name' => '',
        'view_name' => '',
      ),
    ),
    'translatable' => 0,
    'type' => 'node_reference',
  );

  // Exported field_base: 'field_os2web_base_field_rel_subj'
  $field_bases['field_os2web_base_field_rel_subj'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_os2web_base_field_rel_subj',
    'indexes' => array(
      'nid' => array(
        0 => 'nid',
      ),
    ),
    'locked' => 0,
    'module' => 'node_reference',
    'settings' => array(
      'referenceable_types' => array(
        'activity' => 0,
        'borger_dk_permalink' => 0,
        'contentpage' => 0,
        'files' => 0,
        'forum' => 0,
        'iframe_selvbetjeningsl_sning_mm' => 0,
        'institution' => 0,
        'local_plan' => 0,
        'media' => 0,
        'news' => 0,
        'person' => 0,
        'politician' => 0,
        'referat' => 0,
        'right_column' => 0,
        'tema' => 'tema',
        'webform' => 0,
      ),
      'view' => array(
        'args' => array(),
        'display_name' => '',
        'view_name' => '',
      ),
    ),
    'translatable' => 0,
    'type' => 'node_reference',
  );

  // Exported field_base: 'field_subsite_logo'
  $field_bases['field_subsite_logo'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_subsite_logo',
    'indexes' => array(
      'fid' => array(
        0 => 'fid',
      ),
    ),
    'locked' => 0,
    'module' => 'image',
    'settings' => array(
      'default_image' => 0,
      'uri_scheme' => 'public',
    ),
    'translatable' => 0,
    'type' => 'image',
  );

  return $field_bases;
}
