<?php
/**
 * @file
 * Miscelaneous functions for helping out with theme and search.
 */

/**
 * Implements hook_field_formatter_info()
 **/
function os2web_special_field_formatter_info() {
  return array(
    'os2web_special' => array(
      'label' => 'selfservice link',
      'field types' => array('node_reference'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view()
 **/
function os2web_special_field_formatter_view($obj_type, $object, $field, $instance, $langcode, $items, $display) {
  $markup = '<div class="item-list"><ul>';
  if ( !empty($items) ) {
    foreach($items as $item) {
      $node = node_load($item['nid']);

      $title = $node->title;
      
      isset( $node->field_attached_node[LANGUAGE_NONE][0]['nid']) ? $url = drupal_get_path_alias('node/'.$node->field_attached_node[LANGUAGE_NONE][0]['nid']) : false ;
      
      isset( $node->field_selvbetjening_direkte[LANGUAGE_NONE][0]['value']) ? $url = $node->field_selvbetjening_direkte[LANGUAGE_NONE][0]['value'] : false;
      
      
      $markup .= '<li>' . l($title, $url) . '</li>';
    }
  }
  $markup .= '</ul></div>';

  $element[0] = array(
    '#markup' => $markup,
  );

  return $element;
}

/**
 * Implements hook_init().
 *
 * Inject additional Javascripts.
 */
function os2web_special_init() {

  // Only run siteimprove if allowed
  if(variable_get('os2web_special_enable_siteimprove')) {

    $siteimprove_id = variable_get('os2web_special_siteimprove_user_id');

    $script = <<<EOS
      /*<![CDATA[*/
      (function() {
       var sz = document.createElement('script'); sz.type = 'text/javascript'; sz.async = true;
       sz.src = '//ssl.siteimprove.com/js/siteanalyze_{$siteimprove_id}.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(sz, s);
       })();
    /*]]>*/
EOS;
    drupal_add_js($script, array(
      'scope' => 'footer',
      'type' => 'inline',
      'every_page' => TRUE));
  }

}





function os2web_special_menu(){
    $item = array();

    //Admin configuration group
    $item["admin/config/os2web_special"] = array(
        'title' => 'os2web special',
        'description' => 'Administer os2web special settings',
        'access arguments' => array("user access")
    );

    //Admin configuration settings
    $item["admin/config/os2web_special/manage"] = array(
        'title' => 'OS2Web Special settings',
        'description' => 'Manage settings',
        'access arguments' => array("user access"),
        'page callback' => 'drupal_get_form',
        'page arguments' => array("os2web_special_admin_settings_form")
    );

    return $item;
}




/**
 * Implements hook_form()
 * @param $node
 * @param $form_state
 *
 * @return array
 */
function os2web_special_admin_settings_form($node, &$form_state){
    $form = array();

    $form['overview'] = array(
        '#markup' => t("OS2WEB special settings"),
        '#prefix' => "<p>",
        '#suffix' => "</p>"
    );

    // Enable/disable site improve
    $form['os2web_special_enable_siteimprove'] = array(
        '#title' => "Enable siteimprove",
        '#type' => 'checkbox',
        '#required' => false,
        '#default_value' => variable_get("os2web_special_enable_siteimprove")
    );

    // Site improve user id
    $form['os2web_special_siteimprove_user_id'] = array(
        '#title' => "User ID",
        '#type' => 'textfield',
        '#description' => 'Remember to insert your user ID. Ex.: 1480.',
        '#required' => false,
        '#default_value' => variable_get("os2web_special_siteimprove_user_id")
    );
    
    return system_settings_form($form);
}


/**
 * Implements hook_menu_minipanels_styles().
 *
 * Adds extra style selection for minipanel
 */
function os2web_special_menu_minipanels_styles() {
  $styles = array(
    'cmstheme' => t('CMSTheme'),
  );
  return $styles;
}

/**
 * Implements hook_menu_minipanels_style().
 */
function os2web_special_menu_minipanels_style($menu_config) {
  drupal_add_js(drupal_get_path('module', 'os2web_special') . '/menu_style.js', array('scope' => 'footer', 'weight' => 100));
  /* Ekstra til søge-felt */
  // drupal_add_js(drupal_get_path('module', 'os2web_special') . '/search.js', array('scope' => 'header', 'weight' => 100));
  drupal_add_js(drupal_get_path('module', 'os2web_special') . '/jquery.yaselect.min.js', array('scope' => 'header', 'weight' => 102));
  drupal_add_js(drupal_get_path('module', 'os2web_special') . '/jquery.sbselect.js', array('scope' => 'footer', 'weight' => 102));
  drupal_add_js(drupal_get_path('module', 'os2web_special') . '/jquery.tabindex.js', array('scope' => 'footer', 'weight' => 102));
}

/**
 * Implements hook_search_api_ajax_settings().
 */
function os2web_special_search_api_ajax_settings() {
  $settings = array(
    // required: CSS ID for the main content (search results html).
    'content' => '#content .content',
    // required: array of regions with search-related blocks => CSS ID's.
    'regions' => array(
      'my_region' => '#my-css-id',
      'sidebar_first' => '#sidebar-first',
      'sidebar_second' => '#sidebar-second',
    ),
    // optional: if you want to show a spinner image on AJAX.
    'spinner' => drupal_get_path('module', 'search_api_ajax') . '/spinner.gif',
    // optional: if you want to scroll-back-to-top on paging search results.
    'scrolltarget' => '#main-content',
    'scrollspeed' => 1000,
    // optional: fade main content on AJAX (fade=1 for true).
    'fade' => 1,
    'opacity' => 0.3,
  );

  return $settings;
}

function os2web_special_selfservice_links_helper($nid) {
  if(is_numeric($nid)){

  error_log(__FILE__.':'.__LINE__. print_r(node_load($nid), 1)); // tth@bellcom.dk debugging
  }
}
